import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import ParticlesComponent from '@/components/Particles';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='bg-black'>
      <body className={'bg-white mx-auto border'}>
        <div className='relative w-full'>
          <Header />
          {/* <ParticlesComponent /> */}
          <main className='z-50'>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
